CREATE TABLE LOGIN
(
    ID_USUARIO   BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL        VARCHAR(255) UNIQUE NOT NULL,
    SENHA        VARCHAR(100)        NOT NULL,
    ULTIMA_TROCA TIMESTAMP(3)   NOT NULL
);

CREATE TABLE ENDERECO
(
    ID_ENDERECO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO_LOGRADOURO CHAR(20) NOT NULL,
    NOME_LOGRADOURO VARCHAR(60) NOT NULL,
    NUMERO CHAR(20) NOT NULL,
    BAIRRO VARCHAR(40),
    CEP CHAR(09),
    CIDADE CHAR(40),
    UF CHAR(2) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_USUARIO BIGINT NOT NULL PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    ID_ENDERECO BIGINT NOT NULL,
    ULTIMA_ALTERACAO TIMESTAMP(3) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES LOGIN(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) ON DELETE CASCADE

);

CREATE TABLE DONORESTAURANTE (
   ID_USUARIO BIGINT NOT NULL PRIMARY KEY ,
   NOME VARCHAR(60) NOT NULL,
   ID_ENDERECO BIGINT NOT NULL,
   ULTIMA_ALTERACAO TIMESTAMP(3) NOT NULL,
   FOREIGN KEY (ID_USUARIO) REFERENCES LOGIN(ID_USUARIO) ON DELETE CASCADE,
   FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) ON DELETE CASCADE
);
